### ISSUE TITLE
Incorrect Documentation for read Method

### ISSUE THREAD

**Issue by AlexMubarakshin** [VanishMax/foton#6]
Hey!

I noticed an issue with the [documentation for the read method](https://github.com/VanishMax/foton/blob/main/apps/docs/pages/docs/contract-client/read.mdx).

In the provided example, the method field is used like this:

```ts
const res = await contractClient.read({
  method: 'counter',
  arguments: [],
});
```

However, it should be getter instead of method, like so:

```ts
const res = await contractClient.read({
  getter: 'counter',
  arguments: [],
});
```

Thanks!

**Comment by VanishMax** [comment]
Fixed in #7
